### ISSUE TITLE
Is Async support planned?

### ISSUE THREAD

**Issue by PrasannaVenkadesh** [mishankov/yahttp#22]
Hi, thanks for the library. If I am not wrong, the library doesn't support Asynchronous IO. It should be doable as the library relies on `std/httpclient` which have async support. Is it planned?

**Comment by mishankov** [comment]
@PrasannaVenkadesh yes this probably should be done for first major version
You can subscribe for this issue to track progress -  https://github.com/mishankov/yahttp/issues/23
